//this is the styles list of alpacas: those are images sotere in the alpacas folder
const stylesOptionsList = {
  accessories: ["earings", "flower", "glasses", "headphone"],
		backgrounds: [
		"blue50",
	    "blue60",
	    "blue70",
	    "darkblue30",
	    "darkblue50",
	    "darkblue70",
	    "green50",
	    "green60",
	    "green70",
	    "grey40",
	    "grey70",
	    "grey80",
	    "red50",
	    "red60",
	    "red70",
	    "yellow50",
	    "yellow60",
	    "yellow70",
	    "galaxy",
	    "mountains",
	    "art",
	    "wildflowers",
	    "poppy",
	    "sky",
	    "starts",
	    "dakrSky",
	    "violet",
	    "sweets",
	    "pinkHearts",
	    "nature",
	    "emojis",
	    "blueHearts",
	    "clouds",
	    "roses",
	    "pink"
	    ],
	    ears: ["default","tilt-backward","tilt-forward"],
	    eyes: ["angry", "default", "naughty", "panda", "smart", "star"],
	    hair: ["bang", "curls", "default", "elegant", "fancy", "quiff", "short"],
	    leg: ["bubble-tea", "cookie", "default", "game-console", "tilt-backward", "tilt-forward"],
	    mouth: ["astonished", "default", "eating", "laugh", "tongue"],
	    neck: ["bend-backward", "bend-forward", "default", "thick"]
	}

export default stylesOptionsList